name: Create PR to Develop

on:
  pull_request:
    types: [closed]

jobs:
  create_pr_to_develop:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'release'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Reset develop branch
        run: |
          git fetch origin release:release
          git reset --hard release
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: master-promotion
          token: ${{ secrets.GITHUB_TOKEN }} 
