name: Create PR to Develop

on:
  pull_request:
    types: [closed]

jobs:
  create_pr_to_develop:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create PR to Develop
        run: |
          git checkout develop
          git pull origin develop
          git checkout -b pr-from-release
          git merge --no-ff ${{ github.event.pull_request.head.ref }}
          git push origin pr-from-release
          hub pull-request -m "Merge changes from release into develop" -b develop -h pr-from-release
